### ISSUE TITLE
开启热点共享时，连接上的设备走直连

### ISSUE THREAD

**Issue by Rakau** [kalasutra/Clash_Premium_For_Magisk#14]
RT，设备使用流量共享没有用WIFI，面板里的连接信息也看不到有此连接

**Comment by kalasutra** [comment]
是连着wifi的时候开启的热点吗??

**Comment by Rakau** [comment]
> 是连着wifi的时候开启的热点吗??

用的流量

**Comment by kalasutra** [comment]
应该是wifi网卡名不是wlan0的原因

**Comment by Rakau** [comment]
> 应该是wifi网卡名不是wlan0的原因

请问下如何解决?

**Comment by kalasutra** [comment]
模块路径里面有一个clash_tproxy.sh文件,,,有一个wlan0,,,用ip addr查找真实热点网卡名后,,把wlan0改成你查到的网卡名

**Comment by kalasutra** [comment]
iptables -t nat -A AP_PROXY -i wlan0 -p tcp -j REDIRECT --to-port ${clash_redir_port}这一句里面的wlan0改成你查到的热点网卡名,,

**Comment by Rakau** [comment]
> iptables -t nat -A AP_PROXY -i wlan0 -p tcp -j REDIRECT --to-port ${clash_redir_port}这一句里面的wlan0改成你查到的热点网卡名,,

谢谢了,我发现有2个,一个是0一个是1

**Comment by kalasutra** [comment]
现在解决了吗

**Comment by Rakau** [comment]
稍等下，我正在测试

kalasutra <notifications@github.com> 于 2020年12月10日周四 20:53写道：

**Comment by Rakau** [comment]
测试好了，用wlan1可以连上，但模式走的是普通版那个模式，不是TUN，且不支持UDP

**Comment by kalasutra** [comment]
这是正常的,,热点的UDP因为一些原因,并没有做.
