### ISSUE TITLE
getevent -lc 执行卡住导致无法刷入

### ISSUE THREAD

**Issue by HimekoEx** [kalasutra/Clash_Premium_For_Magisk#15]
安卓10, MIUI12稳定版, 红米k304G
经测试 由于是命令 `getevent -lc 1` 卡住导致无法刷入
adb执行命令也是卡住
![image](https://user-images.githubusercontent.com/49508376/101992372-a4849480-3ced-11eb-9b95-9c68a7d2189b.png)
![image](https://user-images.githubusercontent.com/49508376/101992379-b2d2b080-3ced-11eb-81f7-d4121bb2861c.png)

**Comment by kalasutra** [comment]
音量键选择,音量键上键为本地模式,,下键为在线模式

**Comment by HimekoEx** [comment]
> 音量键选择，音量键上键为本地模式，下键为在线模式

感谢
...命令卡住的原因是因为按键没被触发么

**Comment by HimekoEx** [comment]
> 音量键选择，音量键上键为本地模式，下键为在线模式
