### ISSUE TITLE
不同User之间的代理问题

### ISSUE THREAD

**Issue by Sentsuki** [kalasutra/Clash_Premium_For_Magisk#16]
假定使用island，工作空间里的APP也会同时被代理，但如果两个空间里有同一包名的APP，那么如何指定某一个应用不走代理呢？或者像VPN一样实现一用户一代理，这样是否可行？

**Comment by kalasutra** [comment]
没试过这种用法,也没有环境,你可以尝试看一下两个空间里的同一包名的APP的uid是否相同,如果不同,可以尝试用黑名单排除,,或者你把island排除掉试试
